services:
  db-generator:
    image: postgres:18-alpine
    ports:
      - 5432:5432
    env_file:
      .env
    environment:
      POSTGRES_DB: generator
    restart: unless-stopped
    volumes:
      - db-generator-data:/var/lib/postgresql
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d generator"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  storage:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      .env
    volumes:
     - minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  db-generator-data:
  minio-storage:
