// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewPasswordValidatorMock creates a new instance of PasswordValidatorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasswordValidatorMock(t interface {
	mock.TestingT
	Cleanup(func())
},
) *PasswordValidatorMock {
	mock := &PasswordValidatorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PasswordValidatorMock is an autogenerated mock type for the PasswordValidator type
type PasswordValidatorMock struct {
	mock.Mock
}

type PasswordValidatorMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PasswordValidatorMock) EXPECT() *PasswordValidatorMock_Expecter {
	return &PasswordValidatorMock_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type PasswordValidatorMock
func (_mock *PasswordValidatorMock) Validate(password string) error {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PasswordValidatorMock_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type PasswordValidatorMock_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - password string
func (_e *PasswordValidatorMock_Expecter) Validate(password interface{}) *PasswordValidatorMock_Validate_Call {
	return &PasswordValidatorMock_Validate_Call{Call: _e.mock.On("Validate", password)}
}

func (_c *PasswordValidatorMock_Validate_Call) Run(run func(password string)) *PasswordValidatorMock_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PasswordValidatorMock_Validate_Call) Return(err error) *PasswordValidatorMock_Validate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PasswordValidatorMock_Validate_Call) RunAndReturn(run func(password string) error) *PasswordValidatorMock_Validate_Call {
	_c.Call.Return(run)
	return _c
}
