// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewImageValidatorMock creates a new instance of ImageValidatorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImageValidatorMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImageValidatorMock {
	mock := &ImageValidatorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ImageValidatorMock is an autogenerated mock type for the ImageValidator type
type ImageValidatorMock struct {
	mock.Mock
}

type ImageValidatorMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ImageValidatorMock) EXPECT() *ImageValidatorMock_Expecter {
	return &ImageValidatorMock_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type ImageValidatorMock
func (_mock *ImageValidatorMock) Validate(image []byte) error {
	ret := _mock.Called(image)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = returnFunc(image)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ImageValidatorMock_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type ImageValidatorMock_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - image []byte
func (_e *ImageValidatorMock_Expecter) Validate(image interface{}) *ImageValidatorMock_Validate_Call {
	return &ImageValidatorMock_Validate_Call{Call: _e.mock.On("Validate", image)}
}

func (_c *ImageValidatorMock_Validate_Call) Run(run func(image []byte)) *ImageValidatorMock_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ImageValidatorMock_Validate_Call) Return(err error) *ImageValidatorMock_Validate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ImageValidatorMock_Validate_Call) RunAndReturn(run func(image []byte) error) *ImageValidatorMock_Validate_Call {
	_c.Call.Return(run)
	return _c
}
