// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewImageRepositoryMock creates a new instance of ImageRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImageRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImageRepositoryMock {
	mock := &ImageRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ImageRepositoryMock is an autogenerated mock type for the ImageRepository type
type ImageRepositoryMock struct {
	mock.Mock
}

type ImageRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ImageRepositoryMock) EXPECT() *ImageRepositoryMock_Expecter {
	return &ImageRepositoryMock_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type ImageRepositoryMock
func (_mock *ImageRepositoryMock) Save(ctx context.Context, image string) (string, error) {
	ret := _mock.Called(ctx, image)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, image)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, image)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, image)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ImageRepositoryMock_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type ImageRepositoryMock_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - image string
func (_e *ImageRepositoryMock_Expecter) Save(ctx interface{}, image interface{}) *ImageRepositoryMock_Save_Call {
	return &ImageRepositoryMock_Save_Call{Call: _e.mock.On("Save", ctx, image)}
}

func (_c *ImageRepositoryMock_Save_Call) Run(run func(ctx context.Context, image string)) *ImageRepositoryMock_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ImageRepositoryMock_Save_Call) Return(s string, err error) *ImageRepositoryMock_Save_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *ImageRepositoryMock_Save_Call) RunAndReturn(run func(ctx context.Context, image string) (string, error)) *ImageRepositoryMock_Save_Call {
	_c.Call.Return(run)
	return _c
}
