// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/mizentui/fractal-flame/iam/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewUserRepositoryMock creates a new instance of UserRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepositoryMock {
	mock := &UserRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserRepositoryMock is an autogenerated mock type for the UserRepository type
type UserRepositoryMock struct {
	mock.Mock
}

type UserRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepositoryMock) EXPECT() *UserRepositoryMock_Expecter {
	return &UserRepositoryMock_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type UserRepositoryMock
func (_mock *UserRepositoryMock) FindByID(ctx context.Context, id int64) (model.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (model.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) model.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepositoryMock_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type UserRepositoryMock_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *UserRepositoryMock_Expecter) FindByID(ctx interface{}, id interface{}) *UserRepositoryMock_FindByID_Call {
	return &UserRepositoryMock_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *UserRepositoryMock_FindByID_Call) Run(run func(ctx context.Context, id int64)) *UserRepositoryMock_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepositoryMock_FindByID_Call) Return(user model.User, err error) *UserRepositoryMock_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepositoryMock_FindByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (model.User, error)) *UserRepositoryMock_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type UserRepositoryMock
func (_mock *UserRepositoryMock) Update(ctx context.Context, id int64, username string, password string, image string) (model.User, error) {
	ret := _mock.Called(ctx, id, username, password, image)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, string) (model.User, error)); ok {
		return returnFunc(ctx, id, username, password, image)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, string) model.User); ok {
		r0 = returnFunc(ctx, id, username, password, image)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, string, string) error); ok {
		r1 = returnFunc(ctx, id, username, password, image)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepositoryMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UserRepositoryMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - username string
//   - password string
//   - image string
func (_e *UserRepositoryMock_Expecter) Update(ctx interface{}, id interface{}, username interface{}, password interface{}, image interface{}) *UserRepositoryMock_Update_Call {
	return &UserRepositoryMock_Update_Call{Call: _e.mock.On("Update", ctx, id, username, password, image)}
}

func (_c *UserRepositoryMock_Update_Call) Run(run func(ctx context.Context, id int64, username string, password string, image string)) *UserRepositoryMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *UserRepositoryMock_Update_Call) Return(user model.User, err error) *UserRepositoryMock_Update_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepositoryMock_Update_Call) RunAndReturn(run func(ctx context.Context, id int64, username string, password string, image string) (model.User, error)) *UserRepositoryMock_Update_Call {
	_c.Call.Return(run)
	return _c
}
