spring:
  application:
    name: generator
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432}/generator
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  grpc:
    server:
      port: 9090
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml

app:
  generator:
    count: 3
    threads: 3
    max-width: 2000
    max-height: 2000
    max-iterations: 100000000
  jwt-signing-key: ${JWT_SIGNING_KEY}
  s3:
    url: ${MINIO_URL:http://localhost:9000}
    access-key: ${MINIO_ROOT_USER}
    secret-key: ${MINIO_ROOT_PASSWORD}
