spring:
  application:
    name: generator
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432}/generator
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  grpc:
    server:
      port: 9090
      max-inbound-message-size: 16MB
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml

app:
  generator:
    count: 2
    threads: 2
    max-width: ${IMAGE_WIDTH}
    max-height: ${IMAGE_HEIGHT}
    max-iterations: 10000000
    max-symmetry-level: 20
  jwt-signing-key: ${ACCESS_SIGNING_KEY}
  tasks-update-delay: 1s
  s3:
    url: ${MINIO_URL:http://localhost:9000}
    access-key: ${MINIO_ROOT_USER}
    secret-key: ${MINIO_ROOT_PASSWORD}
