spring:
  application:
    name: gateway
  grpc:
    client:
      channels:
        local:
          address: 0.0.0.0:9090
  jackson:
    property-naming-strategy: SNAKE_CASE

app:
  jwt-signing-key: ${JWT_SIGNING_KEY}
