// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/mizentui/fractal-flame/iam/internal/model"
)

// NewUserRepositoryMock creates a new instance of UserRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
},
) *UserRepositoryMock {
	mock := &UserRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserRepositoryMock is an autogenerated mock type for the UserRepository type
type UserRepositoryMock struct {
	mock.Mock
}

type UserRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepositoryMock) EXPECT() *UserRepositoryMock_Expecter {
	return &UserRepositoryMock_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type UserRepositoryMock
func (_mock *UserRepositoryMock) FindByID(ctx context.Context, id int64) (model.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (model.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) model.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepositoryMock_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type UserRepositoryMock_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *UserRepositoryMock_Expecter) FindByID(ctx, id interface{}) *UserRepositoryMock_FindByID_Call {
	return &UserRepositoryMock_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *UserRepositoryMock_FindByID_Call) Run(run func(ctx context.Context, id int64)) *UserRepositoryMock_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepositoryMock_FindByID_Call) Return(user model.User, err error) *UserRepositoryMock_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepositoryMock_FindByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (model.User, error)) *UserRepositoryMock_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUsername provides a mock function for the type UserRepositoryMock
func (_mock *UserRepositoryMock) FindByUsername(ctx context.Context, username string) (model.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindByUsername")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepositoryMock_FindByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUsername'
type UserRepositoryMock_FindByUsername_Call struct {
	*mock.Call
}

// FindByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *UserRepositoryMock_Expecter) FindByUsername(ctx, username interface{}) *UserRepositoryMock_FindByUsername_Call {
	return &UserRepositoryMock_FindByUsername_Call{Call: _e.mock.On("FindByUsername", ctx, username)}
}

func (_c *UserRepositoryMock_FindByUsername_Call) Run(run func(ctx context.Context, username string)) *UserRepositoryMock_FindByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepositoryMock_FindByUsername_Call) Return(user model.User, err error) *UserRepositoryMock_FindByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepositoryMock_FindByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (model.User, error)) *UserRepositoryMock_FindByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type UserRepositoryMock
func (_mock *UserRepositoryMock) Save(ctx context.Context, username, password string) (int64, error) {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return returnFunc(ctx, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepositoryMock_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type UserRepositoryMock_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *UserRepositoryMock_Expecter) Save(ctx, username, password interface{}) *UserRepositoryMock_Save_Call {
	return &UserRepositoryMock_Save_Call{Call: _e.mock.On("Save", ctx, username, password)}
}

func (_c *UserRepositoryMock_Save_Call) Run(run func(ctx context.Context, username, password string)) *UserRepositoryMock_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserRepositoryMock_Save_Call) Return(n int64, err error) *UserRepositoryMock_Save_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *UserRepositoryMock_Save_Call) RunAndReturn(run func(ctx context.Context, username, password string) (int64, error)) *UserRepositoryMock_Save_Call {
	_c.Call.Return(run)
	return _c
}
