// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"github.com/mizentui/fractal-flame/iam/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenManagerMock creates a new instance of TokenManagerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenManagerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenManagerMock {
	mock := &TokenManagerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenManagerMock is an autogenerated mock type for the TokenManager type
type TokenManagerMock struct {
	mock.Mock
}

type TokenManagerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenManagerMock) EXPECT() *TokenManagerMock_Expecter {
	return &TokenManagerMock_Expecter{mock: &_m.Mock}
}

// GenerateTokensPair provides a mock function for the type TokenManagerMock
func (_mock *TokenManagerMock) GenerateTokensPair(user model.User) (model.TokenPair, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTokensPair")
	}

	var r0 model.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(model.User) (model.TokenPair, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(model.User) model.TokenPair); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Get(0).(model.TokenPair)
	}
	if returnFunc, ok := ret.Get(1).(func(model.User) error); ok {
		r1 = returnFunc(user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenManagerMock_GenerateTokensPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTokensPair'
type TokenManagerMock_GenerateTokensPair_Call struct {
	*mock.Call
}

// GenerateTokensPair is a helper method to define mock.On call
//   - user model.User
func (_e *TokenManagerMock_Expecter) GenerateTokensPair(user interface{}) *TokenManagerMock_GenerateTokensPair_Call {
	return &TokenManagerMock_GenerateTokensPair_Call{Call: _e.mock.On("GenerateTokensPair", user)}
}

func (_c *TokenManagerMock_GenerateTokensPair_Call) Run(run func(user model.User)) *TokenManagerMock_GenerateTokensPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.User
		if args[0] != nil {
			arg0 = args[0].(model.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TokenManagerMock_GenerateTokensPair_Call) Return(tokenPair model.TokenPair, err error) *TokenManagerMock_GenerateTokensPair_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *TokenManagerMock_GenerateTokensPair_Call) RunAndReturn(run func(user model.User) (model.TokenPair, error)) *TokenManagerMock_GenerateTokensPair_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRefreshToken provides a mock function for the type TokenManagerMock
func (_mock *TokenManagerMock) ValidateRefreshToken(token string) (int64, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRefreshToken")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int64); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenManagerMock_ValidateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRefreshToken'
type TokenManagerMock_ValidateRefreshToken_Call struct {
	*mock.Call
}

// ValidateRefreshToken is a helper method to define mock.On call
//   - token string
func (_e *TokenManagerMock_Expecter) ValidateRefreshToken(token interface{}) *TokenManagerMock_ValidateRefreshToken_Call {
	return &TokenManagerMock_ValidateRefreshToken_Call{Call: _e.mock.On("ValidateRefreshToken", token)}
}

func (_c *TokenManagerMock_ValidateRefreshToken_Call) Run(run func(token string)) *TokenManagerMock_ValidateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TokenManagerMock_ValidateRefreshToken_Call) Return(n int64, err error) *TokenManagerMock_ValidateRefreshToken_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *TokenManagerMock_ValidateRefreshToken_Call) RunAndReturn(run func(token string) (int64, error)) *TokenManagerMock_ValidateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
