// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewImageServiceMock creates a new instance of ImageServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImageServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImageServiceMock {
	mock := &ImageServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ImageServiceMock is an autogenerated mock type for the ImageService type
type ImageServiceMock struct {
	mock.Mock
}

type ImageServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ImageServiceMock) EXPECT() *ImageServiceMock_Expecter {
	return &ImageServiceMock_Expecter{mock: &_m.Mock}
}

// GetImage provides a mock function for the type ImageServiceMock
func (_mock *ImageServiceMock) GetImage(ctx context.Context, name string) ([]byte, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetImage")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ImageServiceMock_GetImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImage'
type ImageServiceMock_GetImage_Call struct {
	*mock.Call
}

// GetImage is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *ImageServiceMock_Expecter) GetImage(ctx interface{}, name interface{}) *ImageServiceMock_GetImage_Call {
	return &ImageServiceMock_GetImage_Call{Call: _e.mock.On("GetImage", ctx, name)}
}

func (_c *ImageServiceMock_GetImage_Call) Run(run func(ctx context.Context, name string)) *ImageServiceMock_GetImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ImageServiceMock_GetImage_Call) Return(bytes []byte, err error) *ImageServiceMock_GetImage_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *ImageServiceMock_GetImage_Call) RunAndReturn(run func(ctx context.Context, name string) ([]byte, error)) *ImageServiceMock_GetImage_Call {
	_c.Call.Return(run)
	return _c
}
