// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/mizentui/fractal-flame/iam/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthServiceMock creates a new instance of AuthServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthServiceMock {
	mock := &AuthServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthServiceMock is an autogenerated mock type for the AuthService type
type AuthServiceMock struct {
	mock.Mock
}

type AuthServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthServiceMock) EXPECT() *AuthServiceMock_Expecter {
	return &AuthServiceMock_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type AuthServiceMock
func (_mock *AuthServiceMock) Login(ctx context.Context, username string, password string) (model.TokenPair, error) {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 model.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (model.TokenPair, error)); ok {
		return returnFunc(ctx, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) model.TokenPair); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		r0 = ret.Get(0).(model.TokenPair)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthServiceMock_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthServiceMock_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *AuthServiceMock_Expecter) Login(ctx interface{}, username interface{}, password interface{}) *AuthServiceMock_Login_Call {
	return &AuthServiceMock_Login_Call{Call: _e.mock.On("Login", ctx, username, password)}
}

func (_c *AuthServiceMock_Login_Call) Run(run func(ctx context.Context, username string, password string)) *AuthServiceMock_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthServiceMock_Login_Call) Return(tokenPair model.TokenPair, err error) *AuthServiceMock_Login_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *AuthServiceMock_Login_Call) RunAndReturn(run func(ctx context.Context, username string, password string) (model.TokenPair, error)) *AuthServiceMock_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type AuthServiceMock
func (_mock *AuthServiceMock) Refresh(ctx context.Context, refreshToken string) (model.TokenPair, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 model.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.TokenPair, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.TokenPair); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(model.TokenPair)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthServiceMock_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type AuthServiceMock_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *AuthServiceMock_Expecter) Refresh(ctx interface{}, refreshToken interface{}) *AuthServiceMock_Refresh_Call {
	return &AuthServiceMock_Refresh_Call{Call: _e.mock.On("Refresh", ctx, refreshToken)}
}

func (_c *AuthServiceMock_Refresh_Call) Run(run func(ctx context.Context, refreshToken string)) *AuthServiceMock_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthServiceMock_Refresh_Call) Return(tokenPair model.TokenPair, err error) *AuthServiceMock_Refresh_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *AuthServiceMock_Refresh_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (model.TokenPair, error)) *AuthServiceMock_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type AuthServiceMock
func (_mock *AuthServiceMock) Register(ctx context.Context, username string, password string) (int64, error) {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return returnFunc(ctx, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthServiceMock_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type AuthServiceMock_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *AuthServiceMock_Expecter) Register(ctx interface{}, username interface{}, password interface{}) *AuthServiceMock_Register_Call {
	return &AuthServiceMock_Register_Call{Call: _e.mock.On("Register", ctx, username, password)}
}

func (_c *AuthServiceMock_Register_Call) Run(run func(ctx context.Context, username string, password string)) *AuthServiceMock_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthServiceMock_Register_Call) Return(n int64, err error) *AuthServiceMock_Register_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *AuthServiceMock_Register_Call) RunAndReturn(run func(ctx context.Context, username string, password string) (int64, error)) *AuthServiceMock_Register_Call {
	_c.Call.Return(run)
	return _c
}
