syntax = "proto3";

package iam.v1;

import "google/protobuf/wrappers.proto";

option go_package = "github.com/ekuzm/fractal-flame/iam/pkg/proto/iam/v1;iamv1";

service IAMService {
  rpc Register(AuthRequest) returns (RegisterResponse);
  rpc Login(AuthRequest) returns (LoginResponse);
  rpc Refresh(RefreshRequest) returns (RefreshResponse);
  rpc GetUser(GetUserRequest) returns (GetUserResponse);
  rpc ListUsers(ListUsersRequest) returns (ListUsersResponse);
  rpc UpdateUser(UpdateUserRequest) returns (UpdateUserResponse);
}

message AuthRequest {
  string username = 1;
  string password = 2;
}

message RegisterResponse {
  int64 user_id = 1;
}

message LoginResponse {
  string access_token = 1;
  string refresh_token = 2;
}

message RefreshRequest {
  string refresh_token = 1;
}

message RefreshResponse {
  string access_token = 1;
  string refresh_token = 2;
}

message GetUserRequest {
  int64 user_id = 1;
}

message User {
  int64 user_id = 1;
  string username = 2;
  string image = 3;
}

message GetUserResponse {
  User user = 1;
}

message ListUsersRequest {}

message ListUsersResponse {
  repeated User users = 1;
}

message UpdateUserRequest {
  google.protobuf.StringValue username = 1;
}

message UpdateUserResponse {
  User user = 1;
}
