// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewImageRepositoryMock creates a new instance of ImageRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImageRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
},
) *ImageRepositoryMock {
	mock := &ImageRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ImageRepositoryMock is an autogenerated mock type for the ImageRepository type
type ImageRepositoryMock struct {
	mock.Mock
}

type ImageRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ImageRepositoryMock) EXPECT() *ImageRepositoryMock_Expecter {
	return &ImageRepositoryMock_Expecter{mock: &_m.Mock}
}

// FindByName provides a mock function for the type ImageRepositoryMock
func (_mock *ImageRepositoryMock) FindByName(ctx context.Context, name string) ([]byte, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ImageRepositoryMock_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type ImageRepositoryMock_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *ImageRepositoryMock_Expecter) FindByName(ctx, name interface{}) *ImageRepositoryMock_FindByName_Call {
	return &ImageRepositoryMock_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name)}
}

func (_c *ImageRepositoryMock_FindByName_Call) Run(run func(ctx context.Context, name string)) *ImageRepositoryMock_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ImageRepositoryMock_FindByName_Call) Return(bytes []byte, err error) *ImageRepositoryMock_FindByName_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *ImageRepositoryMock_FindByName_Call) RunAndReturn(run func(ctx context.Context, name string) ([]byte, error)) *ImageRepositoryMock_FindByName_Call {
	_c.Call.Return(run)
	return _c
}
